version: "3"
services:
  app:
    build: ./docker
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/app
      - ./docker/server.conf:/etc/nginx/conf.d/default.conf
    links:
      - phpmyadmin
    networks:
      - nginx-proxy
    working_dir: /var/www/app
    stdin_open: true
    tty: true
    container_name: server

  mysql:
     image: mysql:5.6
     volumes:
       - dbdata:/var/lib/mysql
     environment:
        MYSQL_DATABASE: talk
        MYSQL_USER: talk
        MYSQL_PASSWORD: talk
        MYSQL_ROOT_PASSWORD: root
     ports:
        - 3306:3306
     networks:
        - nginx-proxy
     container_name: db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: talk
      PMA_PASSWORD: talk
    networks:
      - nginx-proxy
    restart: always
    ports:
      - 8080:80
    links:
      - mysql

volumes:
  dbdata:

networks:
  nginx-proxy:
     external: false
